facebook_sensitive_words:
  - đối tượng
  - nghi phạm
  - tử vong
  - chết
  - thi thể
  - quyên sinh
  - tự tử
  - tai nạn
  - trọng thương
  - máu
  - vết thương
  - bắt giữ
  - cướp
  - giết
  - sát hại
  - hiếp
  - xâm hại
  - đánh nhau
  - ma túy
  - kích dục
  - vũ khí
  - súng
  - dao
